### PR TITLE
hello_xr: Add Valve Index bindings

### PR DESCRIPTION
**Pull request by ChristophHaag**
... and use trigger/value for grabAction in Vive Controller bindings.

### CODE REVIEW

**Comment by rpavlik** [comment]
@joeludwig ?

**Comment by JoeLudwig** [comment]
Looks good to me.  

I haven't run helloxr with a Vive Controller yet, but I suspect the trigger is easier to deal with than the grip button. I have much the same change locally for the index controllers.

**Comment by rpavlik** [comment]
@christophhaag if you can rebase this or otherwise resolve the conflicts, and add a change log fragment, that would be great, and I'll go ahead and merge it.

**Comment by ChristophHaag** [comment]
Well the grab action is a float action that is used to scale to cube size, and if we bind the Vive Wand's digital grip button we only get the "boring" scales 0.0 and 1.0.

**Review by rpavlik — APPROVED** [review]

**Pull request merged**
