### PR TITLE
Add VS 2022 version code to BUILDING.md

### PR DESCRIPTION
**Pull request by utzcoz**
The VS 2022 version code 17.

### CODE REVIEW

**Comment by utzcoz** [comment]
Looks like `cmake -G "Visual Studio [Version Number] Win64" ../..` is not correct because latest CMake wants something like `Visual Studio 17 2022`.

**Comment by utzcoz** [comment]
Hi @rpavlik , could you help review this PR? Thanks.

**Comment by rpavlik** [comment]
Yep, thanks! I keep meaning to remove this section and just point to the Cmake user instructions but until I get around to it this will help 😁

**Comment by utzcoz** [comment]
@rpavlik I also want to replace it with GitHub Actions' CMake building steps. It might needs extra steps to setup MSVC environment. At least, I can build HelloXR and Loader with CMake + MSVC environment locally. I decide to send a PR for it this weekend if need.

**Pull request merged**
