### PR TITLE
Update build instructions

### PR DESCRIPTION
**Pull request by russell-taylor**
Gets the compile steps working on Linux in Release mode.

### CODE REVIEW

**Comment by rpavlik** [comment]
Good to see you here Russ! Looks good to me, will hold off on the merge because while I can, I'm not sure if I'm supposed to 😁

**Comment by russell-taylor** [comment]
Glad to see this coming out.  I'm looking forward to kicking the tires by porting my Visual Common Ground application from OSVR to OpenXR.

**Review by daveh-lunarg — APPROVED** [review]
Looks good to me.

**Comment by rpavlik** [comment]
One little detail Russ  - apparently the click-thru CLA wasn't enabled yet. Can you go ahead and do it here: https://cla-assistant.io/KhronosGroup/OpenXR-SDK then let us know? (I'd rather not have to roll back merges, etc...)

**Pull request merged**
