### PR TITLE
loader: Don't limit contents of XrInstanceCreateInfo next chain.

### PR DESCRIPTION
**Pull request by rpavlik**
At least a partial fix for #54 - couldn't find any other places where similar logic remained, with a simple search, but may have missed some.

### CODE REVIEW

**Review by daveh-lunarg — CHANGES_REQUESTED** [review]
I think the `ValidateInstanceCreateInfoNextChain` fxn is correct, though incomplete, based on this Valid Usage (Implicit) statement for the XrInstanceCreateInfo struct:
```
Each next member of any structure (including this one) in the next chain must be either NULL
or a pointer to a valid instance of XrDebugUtilsMessengerCreateInfoEXT or
XrInstanceCreateInfoAndroidKHR
```
It looks to me like it should remain, and just add the `XrInstanceCreateInfoAndroidKHR` as an allowed type.

**Comment by rpavlik** [comment]
unfortunately the generated valid usage there is probably wrong since it conflicts with the explicit prose we have elsewhere - see internal issue 1051

**Comment by daveh-lunarg** [comment]
Ok, I'm looking at a 0.9 spec and there's no reason to prohibit unknown structs. It makes me a little uneasy to change code to match what the spec _should have_ said, but it's early days in XR land.

**Review by daveh-lunarg — APPROVED** [review]

**Comment by rpavlik** [comment]
thanks for review! (In any case, it seems a little weird that the loader would validate just this chain, when it's not essential to its job)

**Pull request merged**
