### PR TITLE
Include Win32 loader symbols in release artifact

### PR DESCRIPTION
**Pull request by brycehutchings**
Customers have requested access to the symbols that match the DLLs that we release (both through the .zip artifact and the NuGet package).

### CODE REVIEW

**Review by rpavlik — APPROVED** [review]
Looks reasonable to me - is it worth adding a changelog fragment? or maybe just adding to the one where I put more stuff in the release?

**Comment by brycehutchings** [comment]
> Looks reasonable to me - is it worth adding a changelog fragment? or maybe just adding to the one where I put more stuff in the release?

Yup added!

**Review by rpavlik — APPROVED** [review]

**Comment by rpavlik** [comment]
Have you tried using these PDBs? I tried debugging into it but didn't have any symbols:

image

**Comment by brycehutchings** [comment]
> Have you tried using these PDBs? I tried debugging into it but didn't have any symbols:
> 
> image

That looks like it is using the loader statically linked in, since I don't see openxr_loader.dll in the stack. In that case you need to use the hello_xr.pdb symbol file.

**Comment by rpavlik** [comment]
I literally just downloaded the binaries from the CI there. I think by the time it went boom, it was already out of the loader.

**Comment by brycehutchings** [comment]
> I literally just downloaded the binaries from the CI there. I think by the time it went boom, it was already out of the loader.

If the loader was in the callstack and it was consumed as a DLL then the PDB would help, or if the developer "F11" steps in to a loader (openxr) function then the symbol will allow that.

**Pull request merged**
