### PR TITLE
jnipp: Cherry-pick https://github.com/mitchdowd/jnipp/pull/40

### PR DESCRIPTION
**Pull request by nico**
We use openxr in Chromium, and Chromium's build will break soon if this isn't addressed.

Thanks for your consideration!

### CODE REVIEW

**Comment by nico** [comment]
(ps: I found it a bit confusing that https://github.com/nico/OpenXR-SDK told me to publish the PR here instead of over there.)

**Comment by rpavlik** [comment]
OpenXR-SDK is a derivative of this repo, generated automatically.

(You can run `maintainer-scripts/archive-sdk.sh` to make that repo from this one.)

**Comment by nico** [comment]
Ping :)

(Once this is in, we'll have to update openxr in Chromium, and I'd love to have this done well before libc++ lands its change.)

**Comment by rpavlik** [comment]
This was merged in the private monorepo, will be here upon the upcoming patch release.

**Pull request closed without merging**
