### PR TITLE
Fix exporting of symbols on Windows

### PR DESCRIPTION
**Pull request by rpavlik**
A few things here:

- We now properly tag everything as extern "C" and have simplified the generation. (This fixed the way some symbols were exported on windows with dll loaders)
- We no longer export any LoaderXrTerm functions.
- ~~Build of dynamic loader is fixed on Windows (noticed via my Azure Pipelines non-continuous CI) - have to disable prototypes because the header has no dllexport anymore.~~
- ~~On Windows with dynamic loader, disable tests (and conformance) build because the header never had dllimport. I have no idea how it ever built on Windows with a DLL loader. (If this can be fixed easily, happy to hear how...)~~

UPDATE: We now export undecorated symbols using a .def file. This allows us to skip both dllexport and dllimport. The LOADER_EXPORT macros are still there for non-Windows platforms.

Current list of exported symbols:

```
dumpbin /exports openxr_loader.dll
Microsoft (R) COFF/PE Dumper Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file ..\src\OpenXR-SDK-Source\build\src\loader\openxr_loader.dll

File Type: DLL

  Section contains the following exports for openxr_loader.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
          55 number of functions
          55 number of names

    ordinal hint RVA      name

          1    0 0000E705 xrAcquireSwapchainImage = @ILT+55040(_xrAcquireSwapchainImage@16)
          2    1 00001F73 xrApplyHapticFeedback = @ILT+3950(_xrApplyHapticFeedback@16)
          3    2 0000600F xrAttachSessionActionSets = @ILT+20490(_xrAttachSessionActionSets@12)
          4    3 00004F34 xrBeginFrame = @ILT+16175(_xrBeginFrame@12)
          5    4 0000558D xrBeginSession = @ILT+17800(_xrBeginSession@12)
          6    5 0000B12C xrCreateAction = @ILT+41255(_xrCreateAction@16)
          7    6 0000842C xrCreateActionSet = @ILT+29735(_xrCreateActionSet@16)
          8    7 0000C955 xrCreateActionSpace = @ILT+47440(_xrCreateActionSpace@16)
          9    8 00003DFA xrCreateInstance = @ILT+11765(_xrCreateInstance@8)
         10    9 000068CF xrCreateReferenceSpace = @ILT+22730(_xrCreateReferenceSpace@16)
         11    A 0000B49C xrCreateSession = @ILT+42135(_xrCreateSession@16)
         12    B 00002CF7 xrCreateSwapchain = @ILT+7410(_xrCreateSwapchain@16)
         13    C 0000ADEE xrDestroyAction = @ILT+40425(_xrDestroyAction@8)
         14    D 00003CAB xrDestroyActionSet = @ILT+11430(_xrDestroyActionSet@8)
         15    E 00009377 xrDestroyInstance = @ILT+33650(_xrDestroyInstance@8)
         16    F 0000E1D8 xrDestroySession = @ILT+53715(_xrDestroySession@8)
         17   10 00003846 xrDestroySpace = @ILT+10305(_xrDestroySpace@8)
         18   11 00003F5D xrDestroySwapchain = @ILT+12120(_xrDestroySwapchain@8)
         19   12 00004282 xrEndFrame = @ILT+12925(_xrEndFrame@12)
         20   13 0000DED6 xrEndSession = @ILT+52945(_xrEndSession@8)
         21   14 00003A6C xrEnumerateApiLayerProperties = @ILT+10855(_xrEnumerateApiLayerProperties@12)
         22   15 0000CAA9 xrEnumerateBoundSourcesForAction = @ILT+47780(_xrEnumerateBoundSourcesForAction@24)
         23   16 00004665 xrEnumerateEnvironmentBlendModes = @ILT+13920(_xrEnumerateEnvironmentBlendModes@32)
         24   17 0000BC71 xrEnumerateInstanceExtensionProperties = @ILT+44140(_xrEnumerateInstanceExtensionProperties@16)
         25   18 0000DB07 xrEnumerateReferenceSpaces = @ILT+51970(_xrEnumerateReferenceSpaces@20)
         26   19 00003F44 xrEnumerateSwapchainFormats = @ILT+12095(_xrEnumerateSwapchainFormats@20)
         27   1A 0000985E xrEnumerateSwapchainImages = @ILT+34905(_xrEnumerateSwapchainImages@20)
         28   1B 0000626C xrEnumerateViewConfigurationViews = @ILT+21095(_xrEnumerateViewConfigurationViews@32)
         29   1C 0000AAB5 xrEnumerateViewConfigurations = @ILT+39600(_xrEnumerateViewConfigurations@28)
         30   1D 00007DBF xrGetActionStateBoolean = @ILT+28090(_xrGetActionStateBoolean@16)
         31   1E 0000BF91 xrGetActionStateFloat = @ILT+44940(_xrGetActionStateFloat@16)
         32   1F 00001F19 xrGetActionStatePose = @ILT+3860(_xrGetActionStatePose@16)
         33   20 000053DF xrGetActionStateVector2f = @ILT+17370(_xrGetActionStateVector2f@16)
         34   21 00007982 xrGetCurrentInteractionProfile = @ILT+27005(_xrGetCurrentInteractionProfile@20)
         35   22 000073AB xrGetInputSourceLocalizedName = @ILT+25510(_xrGetInputSourceLocalizedName@24)
         36   23 000089A4 xrGetInstanceProcAddr = @ILT+31135(_xrGetInstanceProcAddr@16)
         37   24 0000A31C xrGetInstanceProperties = @ILT+37655(_xrGetInstanceProperties@12)
         38   25 00003F99 xrGetReferenceSpaceBoundsRect = @ILT+12180(_xrGetReferenceSpaceBoundsRect@16)
         39   26 0000A4CA xrGetSystem = @ILT+38085(_xrGetSystem@16)
         40   27 0000E43F xrGetSystemProperties = @ILT+54330(_xrGetSystemProperties@20)
         41   28 000047FA xrGetViewConfigurationProperties = @ILT+14325(_xrGetViewConfigurationProperties@24)
         42   29 0000C8EC xrLocateSpace = @ILT+47335(_xrLocateSpace@28)
         43   2A 00005E84 xrLocateViews = @ILT+20095(_xrLocateViews@28)
         44   2B 00008F71 xrPathToString = @ILT+32620(_xrPathToString@28)
         45   2C 0000B9A6 xrPollEvent = @ILT+43425(_xrPollEvent@12)
         46   2D 0000B24E xrReleaseSwapchainImage = @ILT+41545(_xrReleaseSwapchainImage@12)
         47   2E 0000B578 xrRequestExitSession = @ILT+42355(_xrRequestExitSession@8)
         48   2F 00007AC7 xrResultToString = @ILT+27330(_xrResultToString@16)
         49   30 0000C96E xrStopHapticFeedback = @ILT+47465(_xrStopHapticFeedback@12)
         50   31 000042FF xrStringToPath = @ILT+13050(_xrStringToPath@16)
         51   32 000037E7 xrStructureTypeToString = @ILT+10210(_xrStructureTypeToString@16)
         52   33 00008B75 xrSuggestInteractionProfileBindings = @ILT+31600(_xrSuggestInteractionProfileBindings@12)
         53   34 00009C96 xrSyncActions = @ILT+35985(_xrSyncActions@12)
         54   35 0000D35F xrWaitFrame = @ILT+50010(_xrWaitFrame@16)
         55   36 00002FDB xrWaitSwapchainImage = @ILT+8150(_xrWaitSwapchainImage@12)

  Summary

        1000 .00cfg
        8000 .data
        2000 .idata
       8A000 .rdata
       17000 .reloc
        1000 .rsrc
      272000 .text
        1000 .tls

```

### CODE REVIEW

**Comment by rpavlik** [comment]
arg - the old DLL has undecorated names as its exports. Presumably that's the difference between needing and not needing dllimport. Guess we need a def after all?

**Comment by rpavlik** [comment]
Updated to fix linking (using undecorated names), etc.

**Comment by rpavlik** [comment]
Loader binaries are here: https://rpavlik.visualstudio.com/OpenXR/_build/results?buildId=59&view=artifacts for testing purposes

**Comment by brycehutchings** [comment]
The extern "C" change looks good. I still don't think I understand what problem there was with using declspec(export). Wouldn't it be simpler to keep Win32 aligned with the other platforms by using declspec(export)?

**Comment by rpavlik** [comment]
the issue is that with declspec(export), it exported the symbols as, e.g. `_xrCreateInstance@8` rather than `xrCreateInstance`, which would probably break people's getprocaddress, as well as actually breaking linking against the DLL with the import lib.

If you know a way to make it not decorate the exported functions so we can just jazz up the LOADER_EXPORT macro again for msvc, I'm all ears :)

**Comment by yl-msft** [comment]
declspec(export) has been working pretty well on functions like xrCreateInstance.  Not sure if there're different views of those exported symbol. 
We do need to avoid declspec(export) on those LoaderXrTerm* functions.

**Review by brycehutchings — APPROVED** [review]

**Comment by rpavlik** [comment]
So the behavior was like this (undecorated exports) prior to the recent export change, the dllexport thing only changed to exporting as stdcall decorated after the reduce-exports PR was merged. (I don't know why.) So 1.0.2 had undecorated exports, just too many of them. After 1.0.2, we got fewer unneeded exports, but they started being decorated ala stdcall names, and this finally gets us back to undecorated and just what we want to export.

**Review by yl-msft — APPROVED** [review]

**Pull request merged**
