### PR TITLE
hello_xr: Vulkan plugin, add check for shaderStorageImageMultisample feature

### PR DESCRIPTION
**Pull request by artyomd**
Added a check for shaderStorageImageMultisample feature and this is fixing issue #233

### CODE REVIEW

**Comment by rpavlik** [comment]
Nice catch! I just ran across #233 myself on Linux.

**Review by rpavlik — APPROVED** [review]
Thanks for the contribution!

**Comment by rpavlik** [comment]
I'll squash those two commits for you and add a changelog fragment too.

**Comment by rpavlik** [comment]
Closing because I just merged it after squashing the clang-format into the other commit.

**Review by Wallbraker — COMMENTED** [review]
Looks good to me

**Pull request closed without merging**
