### PR TITLE
loader: Fix filename and native lib dir sequence for log

### PR DESCRIPTION
**Pull request by utzcoz**

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @rpavlik , could you help to review this PR? Thanks.

**Comment by rpavlik** [comment]
Looks good, can you add a changelog fragment in changes/sdk? See readme in there

**Comment by utzcoz** [comment]
> Looks good, can you add a changelog fragment in changes/sdk? See readme in there

Hi @rpavlik , I added a new commit to add changelog fragment based on previous PRs. If it doesn't meet requirement, please let me know.

**Review by rpavlik — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
