### PR TITLE
fix minor substr error

### PR DESCRIPTION
**Pull request by zheqiMicrosoft**
There is a minor bug with substring usage. Remove the "- 1" that's unnecessary.

### CODE REVIEW

**Review by yl-msft — APPROVED** [review]

**Comment by rpavlik** [comment]
So this was put in by a Linux dev, IIRC. Only risk I see is that it might result in a doubled-up path character (/ or \) in its usage, which I wouldn't expect to be harmful, but not sure. What is the actual bug being corrected here?

**Comment by zheqiMicrosoft** [comment]
> hat is the actual bug being corrected here?

**Comment by zheqiMicrosoft** [comment]
The question I believe is that in windows when the path is "D:\chromium2\src\out\Debug\loader.dll" the parent path will be "D:\chromium2\src\out\Debu" instead of ""D:\chromium2\src\out\Debug".

**Comment by patrto** [comment]
> So this was put in by a Linux dev, IIRC. Only risk I see is that it might result in a doubled-up path character (/ or ) in its usage, which I wouldn't expect to be harmful, but not sure. What is the actual bug being corrected here?

In Windows, the -1 is truncating the parent path of the runtime:
C:\Windows\System32\OpenXRRuntime.dll -> C:\Windows\System3\OpenXRRuntime.dll

Is there a Linux case that breaks without the -1?

**Comment by yl-msft** [comment]
> Is there a Linux case that breaks without the -1?

isn't this a windows only code path?  not sure how can Linux be affected by this change.

**Comment by rpavlik** [comment]
Sounds good to me. I just remember that line being added by (iirc) a primarily-Linux dev. I'm not as familiar with that piece of the loader.

**Pull request merged**
