### PR TITLE
 MinGW build fix

### PR DESCRIPTION
**Pull request by brainrom**
`.def` and `.pdb` are MSVC-specific resources. MinGW can correctly build the OpenXR loader, but only with these changes.

### CODE REVIEW

**Comment by rpavlik** [comment]
The one thing I'm not sure about, is that I am pretty sure that LLVM/Clang on Windows can make PDB's. I was hoping CMake would have a variable or property that says "this toolchain makes pdb" but I haven't found one.  This is an improvement but I wonder if we can flip the condition, only exclude for mingw?

**Comment by brainrom** [comment]
Hmm. Okay, then `if(WIN32 AND NOT MINGW AND DYNAMIC_LOADER)`?

**Comment by brainrom** [comment]
Changed the condition.

**Review by rpavlik — APPROVED** [review]

**Comment by rpavlik** [comment]
Thanks very much!

**Comment by rpavlik** [comment]
We received #387 to correct the exported symbols, which effectively undoes this. Can you work with that submitter to figure out the correct answer here that will work for both of you?

**Pull request merged**
